// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Risk_Management_RiskEX_Backend.Data;

#nullable disable

namespace Risk_Management_RiskEX_Backend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241228091617_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentBasis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AssessmentsBasis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Basis = "Confidentiality",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3405),
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3406)
                        },
                        new
                        {
                            Id = 2,
                            Basis = "Integrity",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3408),
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3409)
                        },
                        new
                        {
                            Id = 3,
                            Basis = "Privacy",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3411),
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3412)
                        },
                        new
                        {
                            Id = 4,
                            Basis = "Quality",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3413),
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3414)
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixImpact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<double>("Impact")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AssessmentsMatrixImpact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssessmentFactor = "Low",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3501),
                            Definition = "No/slight effect on business",
                            Impact = 10.0,
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3502)
                        },
                        new
                        {
                            Id = 2,
                            AssessmentFactor = "Medium",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3505),
                            Definition = "business objectives affected",
                            Impact = 20.0,
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3506)
                        },
                        new
                        {
                            Id = 3,
                            AssessmentFactor = "High",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3508),
                            Definition = "business objectives undermined",
                            Impact = 40.0,
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3509)
                        },
                        new
                        {
                            Id = 4,
                            AssessmentFactor = "Critical",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3511),
                            Definition = "business objectives not accomplished",
                            Impact = 60.0,
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3512)
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixLikelihood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<double>("Likelihood")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AssessmentsMatrixLikelihood");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssessmentFactor = "Low",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3546),
                            Definition = "1-24% chance of occurrence",
                            Likelihood = 0.10000000000000001,
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3547)
                        },
                        new
                        {
                            Id = 2,
                            AssessmentFactor = "Medium",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3550),
                            Definition = "25-49% chance of occurrence",
                            Likelihood = 0.20000000000000001,
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3550)
                        },
                        new
                        {
                            Id = 3,
                            AssessmentFactor = "High",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3553),
                            Definition = "50-74% chance of occurrence",
                            Likelihood = 0.40000000000000002,
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3554)
                        },
                        new
                        {
                            Id = 4,
                            AssessmentFactor = "Critical",
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3557),
                            Definition = "75-99% chance of occurrence",
                            Likelihood = 0.59999999999999998,
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3557)
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(2906),
                            DepartmentName = "SFM",
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(2916)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(2920),
                            DepartmentName = "HR",
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(2922)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(2924),
                            DepartmentName = "Finance",
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(2925)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(2927),
                            DepartmentName = "IT",
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(2929)
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.ExternalReviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("ExternalReviewers");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3464),
                            CreatedById = 1,
                            DepartmentId = 1,
                            Name = "Data Center Migration",
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3465),
                            UpdatedById = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3469),
                            CreatedById = 1,
                            DepartmentId = 2,
                            Name = "HR Inventory",
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3470),
                            UpdatedById = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int?>("ExternalReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ExternalReviewerId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Contingency")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Mitigation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OverallRiskRating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PlannedActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("ResponsibleUserId")
                        .HasColumnType("integer");

                    b.Property<string>("RiskId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RiskName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("RiskResponseId")
                        .HasColumnType("integer");

                    b.Property<int?>("RiskStatus")
                        .HasColumnType("integer");

                    b.Property<int>("RiskType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("RiskResponseId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssessmentBasisId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("Impact")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMitigated")
                        .HasColumnType("boolean");

                    b.Property<int>("Likelihood")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<int>("RiskFactor")
                        .HasColumnType("integer");

                    b.Property<int>("RiskId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentBasisId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Impact");

                    b.HasIndex("Likelihood");

                    b.HasIndex("ReviewId");

                    b.HasIndex("RiskId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.RiskResponseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RiskResponseDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This strategy aims to eliminate the risk entirely by taking actions that prevent the risk from occurring. It involves altering project plans or processes to steer clear of the risk's potential impact.",
                            Example = "Changing a project scope to exclude a high-risk feature that could lead to technical challenges.",
                            Name = "Avoid"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mitigation involves taking proactive steps to reduce the likelihood or impact of a risk. It focuses on minimizing the risk's negative effects while still allowing the project or function to move forward.",
                            Example = "Developing a backup system to reduce the impact of potential server failures.",
                            Name = "Mitigate"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Transferring the risk involves shifting the responsibility for managing the risk to another party. This could be achieved through insurance, outsourcing, partnerships, or contracts.",
                            Example = "Purchasing insurance to cover financial losses due to unforeseen events.",
                            Name = "Transfer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Accepting the risk means acknowledging its existence and choosing not to take specific actions to mitigate or avoid it.",
                            Example = "Deciding not to invest in additional security for a low-value system because the cost of mitigation exceeds the potential impact of the risk.",
                            Name = "Accept"
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3350),
                            DepartmentId = 1,
                            Email = "admin@riskex.com",
                            FullName = "System Admin",
                            IsActive = true,
                            Password = "Admin@123",
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3351)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3355),
                            DepartmentId = 1,
                            Email = "risk.manager@riskex.com",
                            FullName = "Risk Manager",
                            IsActive = true,
                            Password = "Risk@123",
                            UpdatedAt = new DateTime(2024, 12, 28, 9, 16, 17, 310, DateTimeKind.Utc).AddTicks(3356)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.ExternalReviewer", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedExternalReviewers")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Department", "Department")
                        .WithMany("ExternalReviewers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedExternalReviewers")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Project", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedProjects")
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Review", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedReviews")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.ExternalReviewer", "ExternalReviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ExternalReviewerId");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedReviews")
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("ExternalReviewer");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Risk", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedRisks")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Department", "Department")
                        .WithMany("Risks")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Project", "Project")
                        .WithMany("Risks")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "ResponsibleUser")
                        .WithMany("ResponsibleRisks")
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.RiskResponseData", "RiskResponseData")
                        .WithMany("Risks")
                        .HasForeignKey("RiskResponseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedRisks")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("Project");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("RiskResponseData");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.RiskAssessment", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.AssessmentBasis", "AssessmentBasis")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("AssessmentBasisId");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixImpact", "MatrixImpact")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("Impact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixLikelihood", "MatrixLikelihood")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("Likelihood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Review", "Review")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Risk", "Risk")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("AssessmentBasis");

                    b.Navigation("CreatedBy");

                    b.Navigation("MatrixImpact");

                    b.Navigation("MatrixLikelihood");

                    b.Navigation("Review");

                    b.Navigation("Risk");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.User", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedUsers")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentBasis", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixImpact", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixLikelihood", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Department", b =>
                {
                    b.Navigation("ExternalReviewers");

                    b.Navigation("Projects");

                    b.Navigation("Risks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.ExternalReviewer", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Project", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Review", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Risk", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.RiskResponseData", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.User", b =>
                {
                    b.Navigation("CreatedExternalReviewers");

                    b.Navigation("CreatedProjects");

                    b.Navigation("CreatedReviews");

                    b.Navigation("CreatedRisks");

                    b.Navigation("CreatedUsers");

                    b.Navigation("Projects");

                    b.Navigation("ResponsibleRisks");

                    b.Navigation("Reviews");

                    b.Navigation("UpdatedExternalReviewers");

                    b.Navigation("UpdatedProjects");

                    b.Navigation("UpdatedReviews");

                    b.Navigation("UpdatedRisks");

                    b.Navigation("UpdatedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
