// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Risk_Management_RiskEX_Backend.Data;

#nullable disable

namespace Risk_Management_RiskEX_Backend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250805100338_Rework")]
    partial class Rework
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ProjectUser");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentBasis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Basis")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("AssessmentsBasis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Basis = "Confidentiality",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8967),
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8968)
                        },
                        new
                        {
                            Id = 2,
                            Basis = "Integrity",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8969),
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8970)
                        },
                        new
                        {
                            Id = 3,
                            Basis = "Availability",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8971),
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8971)
                        },
                        new
                        {
                            Id = 4,
                            Basis = "Privacy",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8973),
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8973)
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixImpact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentFactor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<double>("Impact")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("AssessmentsMatrixImpact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssessmentFactor = "Low",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8992),
                            Definition = "No slight effect on business",
                            Impact = 10.0,
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8993)
                        },
                        new
                        {
                            Id = 2,
                            AssessmentFactor = "Medium",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8994),
                            Definition = "Business objectives affected",
                            Impact = 20.0,
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8995)
                        },
                        new
                        {
                            Id = 3,
                            AssessmentFactor = "High",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8996),
                            Definition = "Business objectives undermined",
                            Impact = 40.0,
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8997)
                        },
                        new
                        {
                            Id = 4,
                            AssessmentFactor = "Critical",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8998),
                            Definition = "Business objectives not accomplished",
                            Impact = 60.0,
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8998)
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixLikelihood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentFactor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<double>("Likelihood")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("AssessmentsMatrixLikelihood");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssessmentFactor = "Low",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(9020),
                            Definition = "1-24% chance of occurrence",
                            Likelihood = 0.10000000000000001,
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(9021)
                        },
                        new
                        {
                            Id = 2,
                            AssessmentFactor = "Medium",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(9022),
                            Definition = "25-49% chance of occurrence",
                            Likelihood = 0.20000000000000001,
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(9023)
                        },
                        new
                        {
                            Id = 3,
                            AssessmentFactor = "High",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(9024),
                            Definition = "50-74% chance of occurrence",
                            Likelihood = 0.40000000000000002,
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(9025)
                        },
                        new
                        {
                            Id = 4,
                            AssessmentFactor = "Critical",
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(9026),
                            Definition = "75-99% chance of occurrence",
                            Likelihood = 0.59999999999999998,
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(9027)
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("text");

                    b.Property<string>("NewName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8729),
                            DepartmentCode = "ACE",
                            DepartmentName = "Audits & Compliance",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8733)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8734),
                            DepartmentCode = "EMT",
                            DepartmentName = "EMT",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8735)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8737),
                            DepartmentCode = "SFM",
                            DepartmentName = "SFM",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8737)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8774),
                            DepartmentCode = "HR",
                            DepartmentName = "HR",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8774)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8775),
                            DepartmentCode = "A&D",
                            DepartmentName = "Admin & Purchase",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8776)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8777),
                            DepartmentCode = "DU1",
                            DepartmentName = "DU1",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8778)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8779),
                            DepartmentCode = "DU2",
                            DepartmentName = "DU2",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8780)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8781),
                            DepartmentCode = "DU3",
                            DepartmentName = "DU3",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8781)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8782),
                            DepartmentCode = "DU4",
                            DepartmentName = "DU4",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8783)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8784),
                            DepartmentCode = "DU5",
                            DepartmentName = "DU5",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8785)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8786),
                            DepartmentCode = "DU6",
                            DepartmentName = "DU6",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8786)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8788),
                            DepartmentCode = "MAR",
                            DepartmentName = "Marketing",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8788)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8789),
                            DepartmentCode = "L&D",
                            DepartmentName = "Learning & Development",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8790)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8791),
                            DepartmentCode = "FIN",
                            DepartmentName = "Finance",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8791)
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.ExternalReviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("ExternalReviewers");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int?>("ExternalReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ExternalReviewerId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Contingency")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ISOClauseNumber")
                        .HasColumnType("text");

                    b.Property<string>("Impact")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Mitigation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("OverallRiskRatingAfter")
                        .HasColumnType("integer");

                    b.Property<int>("OverallRiskRatingBefore")
                        .HasColumnType("integer");

                    b.Property<double?>("PercentageRedution")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PlannedActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int?>("ResidualRisk")
                        .HasColumnType("integer");

                    b.Property<int?>("ResidualValue")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsibleUserId")
                        .HasColumnType("integer");

                    b.Property<string>("RiskId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RiskName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RiskResponseId")
                        .HasColumnType("integer");

                    b.Property<int>("RiskStatus")
                        .HasColumnType("integer");

                    b.Property<int>("RiskType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("RiskResponseId");

                    b.HasIndex("RiskStatus");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("DepartmentId", "RiskStatus");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.RiskAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssessmentBasisId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("Impact")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMitigated")
                        .HasColumnType("boolean");

                    b.Property<int>("Likelihood")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<int>("RiskFactor")
                        .HasColumnType("integer");

                    b.Property<int>("RiskId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentBasisId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Impact");

                    b.HasIndex("Likelihood");

                    b.HasIndex("ReviewId");

                    b.HasIndex("RiskId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.RiskResponseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RiskResponseDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This strategy aims to eliminate the risk entirely by taking actions that prevent the risk from occurring. It involves altering project plans or processes to steer clear of the risk's potential impact.",
                            Example = "Changing a project scope to exclude a high-risk feature that could lead to technical challenges.",
                            Name = "Avoid"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mitigation involves taking proactive steps to reduce the likelihood or impact of a risk. It focuses on minimizing the risk's negative effects while still allowing the project or function to move forward.",
                            Example = "Developing a backup system to reduce the impact of potential server failures.",
                            Name = "Mitigate"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Transferring the risk involves shifting the responsibility for managing the risk to another party. This could be achieved through insurance, outsourcing, partnerships, or contracts.",
                            Example = "Purchasing insurance to cover financial losses due to unforeseen events.",
                            Name = "Transfer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Accepting the risk means acknowledging its existence and choosing not to take specific actions to mitigate or avoid it.",
                            Example = "Deciding not to invest in additional security for a low-value system because the cost of mitigation exceeds the potential impact of the risk.",
                            Name = "Accept"
                        });
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8939),
                            DepartmentId = 1,
                            Email = "riskex@experionglobal.com",
                            FullName = "System Admin",
                            IsActive = true,
                            Password = "AQAAAAIAAYagAAAAEAaroqhRU1q5tzEl35QYww+8xRNB3KLD6rrlXLdANJ8N2kUrAXvLsEYOpWldjgmzMg==",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8939)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8941),
                            DepartmentId = 1,
                            Email = "admin@gmail.com",
                            FullName = "System Admin",
                            IsActive = true,
                            Password = "AQAAAAIAAYagAAAAEAaroqhRU1q5tzEl35QYww+8xRNB3KLD6rrlXLdANJ8N2kUrAXvLsEYOpWldjgmzMg==",
                            UpdatedAt = new DateTime(2025, 8, 5, 10, 3, 37, 253, DateTimeKind.Utc).AddTicks(8942)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectUser", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.ExternalReviewer", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedExternalReviewers")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Department", "Department")
                        .WithMany("ExternalReviewers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedExternalReviewers")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Project", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedProjects")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Review", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedReviews")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.ExternalReviewer", "ExternalReviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ExternalReviewerId");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedReviews")
                        .HasForeignKey("UpdatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("ExternalReviewer");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Risk", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedRisks")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Department", "Department")
                        .WithMany("Risks")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Project", "Project")
                        .WithMany("Risks")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "ResponsibleUser")
                        .WithMany("ResponsibleRisks")
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.RiskResponseData", "RiskResponseData")
                        .WithMany("Risks")
                        .HasForeignKey("RiskResponseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedRisks")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("Project");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("RiskResponseData");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.RiskAssessment", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.AssessmentBasis", "AssessmentBasis")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("AssessmentBasisId");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixImpact", "MatrixImpact")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("Impact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixLikelihood", "MatrixLikelihood")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("Likelihood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Review", "Review")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Risk", "Risk")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("AssessmentBasis");

                    b.Navigation("CreatedBy");

                    b.Navigation("MatrixImpact");

                    b.Navigation("MatrixLikelihood");

                    b.Navigation("Review");

                    b.Navigation("Risk");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.User", b =>
                {
                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "CreatedBy")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Risk_Management_RiskEX_Backend.Models.User", "UpdatedBy")
                        .WithMany("UpdatedUsers")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Department");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentBasis", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixImpact", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.AssessmentMatrixLikelihood", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Department", b =>
                {
                    b.Navigation("ExternalReviewers");

                    b.Navigation("Projects");

                    b.Navigation("Risks");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.ExternalReviewer", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Project", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Review", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.Risk", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.RiskResponseData", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("Risk_Management_RiskEX_Backend.Models.User", b =>
                {
                    b.Navigation("CreatedExternalReviewers");

                    b.Navigation("CreatedProjects");

                    b.Navigation("CreatedReviews");

                    b.Navigation("CreatedRisks");

                    b.Navigation("CreatedUsers");

                    b.Navigation("ResponsibleRisks");

                    b.Navigation("Reviews");

                    b.Navigation("UpdatedExternalReviewers");

                    b.Navigation("UpdatedProjects");

                    b.Navigation("UpdatedReviews");

                    b.Navigation("UpdatedRisks");

                    b.Navigation("UpdatedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
